// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-me4e1sWPy7PfoaKUbOH2SRr6uw7MVM',
    appId: '1:491045312453:web:debe587f78516495639dac',
    messagingSenderId: '491045312453',
    projectId: 'video-study-platform',
    authDomain: 'video-study-platform.firebaseapp.com',
    storageBucket: 'video-study-platform.firebasestorage.app',
    measurementId: 'G-V5NKFC84C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK7lwetY0mZIFHQAhr22OAhd5_F-SnUIc',
    appId: '1:491045312453:android:7c58ff5b3160aff0639dac',
    messagingSenderId: '491045312453',
    projectId: 'video-study-platform',
    storageBucket: 'video-study-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0S1Np1xxrGqNVm_QouAn8AgAdKRsqfzc',
    appId: '1:491045312453:ios:9f099ea0ee9feab4639dac',
    messagingSenderId: '491045312453',
    projectId: 'video-study-platform',
    storageBucket: 'video-study-platform.firebasestorage.app',
    iosBundleId: 'com.example.videoStudyPlatform',
  );

}
